language: node_js

node:
  - "10"
  - "11"
  - "12"

before_script:
  - npm install --dev

cache:
  npm: false

script:
  - npm test

branches:
  except:
    - dev

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows

after_success: npm run coverage
